=pod

=encoding utf8

=head1 NAME

B<Fancy::Open> opens a file and creates an array with an optional prefix, suffix, or both in your preferred encoding.

=head1 VERSION

This document describes Fancy::Open version 1.0.

=head1 SYNOPSIS

  use Fancy::Open qw(fancy_open);

  my @plain_array   = fancy_open($file);

  my @prefix_array  = fancy_open($file, { 'prefix' => 'foo' });

  my @suffix_array  = fancy_open($file, { 'suffix' => 'bar; });

  my @both_array    = fancy_open($file, { 'prefix' => 'foo', 'suffix' => 'bar' });

  my @encoded_array = fancy_open($file, { 'encoding' => 'ascii' });

=head1 DESCRIPTION

C<fancy_open> can be exported and returns a list of values. These values can be modified if the optional parameters C<prefix>, C<suffix>, or both are used. There is the additional option to choose your C<encoding>, the default is C<utf-8>.

If the open fails, fancy_open will die.

  my @fancy_array = fancy_open($file, { 'prefix' => $prefix_value, 'suffix' => $suffix_value });

The file is also closed by C<fancy_open>.

C<Fancy::Open> requires Perl version 5.10.0 or better.

=head2 Parameters

C<fancy_open> has two parameters.

=head3 file

  my @plain_array  = fancy_open($file);

The first parameter is the file to be opened. If this is the only parameter specified, the file will be opened, encoded to C<utf-8>, and returned as a list.

=head3 Options

The second parameter are the options: C<prefix>, C<suffix>, and C<encoding>.

=head4 prefix

  my @prefix_array = fancy_open($file, { 'prefix' => 'foo' });

The C<prefix> option is the string you want prepended to each item in the list. Using the example, all items on the list will be returned with C<foo> prepended to them.

  foofoo
  foobar
  foobaz
  fooqux

=head4 suffix

  my @suffix_array  = fancy_open($file, { 'suffix' => 'bar; });

The C<suffix> option is the string you want to appear appended to each item in the list. Using the example, all items on the list will be returned with C<bar> appended to them.

  foobar
  barbar
  bazbar
  quxbar

=head4 prefix and suffix

  my @both_array   = fancy_open($file, { 'prefix' => 'foo', 'suffix' => 'bar' });

Using both the C<prefix> and C<suffix> options together will prepend and append the associated strings to the items in the list.

  foofoobar
  foobarbar
  foobazbar
  fooquxbar

=head4 encoding

  my @encoded_array = fancy_open($file, { 'encoding' => 'ascii' });

The C<encoding> option is the encoding you want to use to open the file. The above file will be opened C<ascii> encoded.

=head1 DEPENDENCY

Fancy::Open depends on L<Exporter>.

=head1 AUTHOR

Lady Aleena

=head1 LICENSE AND COPYRIGHT

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself. See L<perlartistic>.

Copyright © 2020, Lady Aleena C<(aleena@cpan.org)>. All rights reserved.

=cut
