=pod

=encoding utf8

=head1 NAME

B<Fancy::Open> opens and creates an array for a file.

=head1 VERSION

This document describes Fancy::Open version 1.0.

=head1 SYNOPSIS

  use Fancy::Open qw(fancy_open);

  my @plain_array   = fancy_open($file);

  my @before_array  = fancy_open($file, { 'before' => 'foo' });

  my @after_array   = fancy_open($file, { 'after' => 'bar; });

  my @both_array    = fancy_open($file, { 'before' => 'foo', 'after' => 'bar' });

  my @encoded_array = fancy_open($file, { 'encoding' => 'ascii' });

=head1 DESCRIPTION

C<fancy_open> can be exported and returns a list of values. These values can be modified if the optional parameters C<before>, C<after>, or both are used. There is the additional option to choose your C<encoding>, the default is C<uft-8>.

If the open fails, fancy_open will die with a message with the file and the captured error.

  my @fancy_array = fancy_open($file, { 'before' => $before_value, 'after' => $after_value });

=head2 Parameters

C<fancy_open> has two parameters.

=head3 file

  my @plain_array  = fancy_open($file);

The first parameter is the file to be opened. If this is the only parameter specified, the file will be opened, encoded to C<utf-8>, and returned as a list.

=head3 Options

The second parameter are the options: C<before>, C<after>, and C<encoding>.

=head4 before

  my @before_array = fancy_open($file, { 'before' => 'foo' });

The C<before> option is the string you want prepended to each item in the list. Using the example, all items on the list will be returned with C<foo> prepended to them.

  foofoo
  foobar
  foobaz
  fooqux

=head4 after

  my @after_array  = fancy_open($file, { 'after' => 'bar; });

The C<after> option is the string you want to appear appended to each item in the list. Using the example, all items on the list will be returned with C<bar> appended to them.

  foobar
  barbar
  bazbar
  quxbar

=head4 before and after

  my @both_array   = fancy_open($file, { 'before' => 'foo', 'after' => 'bar' });

Using both the C<before> and C<after> options together will prepend and append the associated strings to the items in the list.

  foofoobar
  foobarbar
  foobazbar
  fooquxbar

=head4 encoding

  my @encoded_array = fancy_open($file, { 'encoding' => 'ascii' });

The C<encoding> option is the encoding you want to use to open the file. The above file will be opened C<ascii> encoded.

=head1 DEPENDENCY

Fancy::Open depends on L<Exporter>.

=head1 AUTHOR

Lady Aleena

=head1 LICENSE AND COPYRIGHT

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself. See L<perlartistic>.

Copyright © 2020, Lady Aleena C<(aleena@cpan.org)>. All rights reserved.

=cut
